# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    default_release: "{{ item.codename | default(omit) }}"
  with_items: "{{ hp_proliant_support_pack_install }}"
  tags:
    - hp-proliant-support-pack-install-dependencies
