# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_facts['distribution_release'] }}.yml"
    - "_{{ ansible_facts['distribution'] | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - hp-proliant-support-pack

- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - hp-proliant-support-pack
    - hp-proliant-support-pack-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - hp-proliant-support-pack
    - hp-proliant-support-pack-install
