# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - hp-proliant-support-pack
    - hp-proliant-support-pack-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - hp-proliant-support-pack
    - hp-proliant-support-pack-install
