# tasks file
---
- name: repository | dependencies
  ansible.builtin.apt:
    name: "{{ hp_proliant_support_pack_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - hp-proliant-support-pack-repository-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: "{{ item.id }}"
    keyserver: "{{ apt_key_keyserver | default('keyserver.ubuntu.com') }}"
    state: present
  with_items: "{{ hp_proliant_support_pack_apt_keys }}"
  tags:
    - hp-proliant-support-pack-repository-public-key

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ hp_proliant_support_pack_repositories }}"
  tags:
    - hp-proliant-support-pack-repository-add
